repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff Lint
        entry: uv run ruff check --fix
        language: system
        types: [python]

      - id: ruff-format
        name: Ruff Format
        entry: uv run ruff format
        language: system
        types: [python]

      - id: run-pytest
        name: Pytest
        entry: uv run pytest
        language: system
        types: [python]

