name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    environment:
      name: production
  
    steps:
      - uses: actions/checkout@v3
  
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.14"
  
      - name: Install dependencies
        run: uv sync --dev
  
      - name: Build package
        run: |
          uv build
  
      - name: Generate sample data
        run: |
          rm -rf sample_data
          uv run generate-sample-data --output-dir sample_data
  
      - name: Zip sample data
        run: |
          zip -r sample_data_${{ github.ref_name }}.zip sample_data/

      - name: Extract release notes
        uses: ffurrer2/extract-release-notes@v2
        with:
          release_notes_file: RELEASE_NOTES.md
  
      - name: Upload Python package to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.tar.gz
            dist/*.whl
          body_path: RELEASE_NOTES.md
          token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Upload sample data to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: sample_data_${{ github.ref_name }}.zip
  
      - name: Upload to PyPI
        run: uv publish --trusted-publishing always
  
